light_switch:
    path:     /light/switch/{switch}
    defaults: { _controller: light_controller:switchAction }
    
light_status:
    path:     /light/status
    defaults: { _controller: light_controller:statusAction }